# Generated by Django 3.1.1 on 2020-09-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studendts',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studendts',
            name='adress',
            field=models.CharField(max_length=50),
        ),
    ]
