# Generated by Django 3.1.1 on 2020-09-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_auto_20200904_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('math', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=50)),
                ('science', models.CharField(max_length=50)),
            ],
        ),
    ]
